### ISSUE TITLE
TLS handshake error with K8s 1.19.x

### ISSUE THREAD

**Issue by smg-bg** [mk811/sts-annotator#2]
``I've upgraded my AKS cluster from 1.18.x to 1.19.11. After the upgrade I had to update the MutatingWebhookConfiguration to v1 (v1beta was deprecated). 

```yaml

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sts-annotator
  namespace: sts-annotator
webhooks:
  - name: sts-annotator.sts-annotator.svc
    clientConfig:
      service:
        name: sts-annotator
        path: /v1/sts/pod/annotation
        namespace: sts-annotator
      caBundle: <CA Bundle>
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - pods
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]

```

The problem is that I'm getting TLS handshake errors afterwards. Double checked the certificates and they are valid. Still, just in case I regenrated new ones. Here is the output of the sts-annotator pod: 

```bash
$  k logs -n sts-annotator sts-annotator-d4d989cf5-nhtrn
{"level":"info","time":"2021-06-06T09:34:38Z","message":"Log Level: debug"}
2021/06/06 09:35:20 http: TLS handshake error from 10.77.77.42:59456: remote error: tls: bad certificate
2021/06/06 09:35:20 http: TLS handshake error from 10.77.77.42:59458: remote error: tls: bad certificate
2021/06/06 09:35:21 http: TLS handshake error from 10.77.77.42:59464: remote error: tls: bad certificate
2021/06/06 09:35:21 http: TLS handshake error from 10.77.77.42:59476: remote error: tls: bad certificate
2021/06/06 09:35:21 http: TLS handshake error from 10.77.77.42:59480: remote error: tls: bad certificate
2021/06/06 09:35:21 http: TLS handshake error from 10.77.77.42:59490: remote error: tls: bad certificate
2021/06/06 09:35:21 http: TLS handshake error from 10.77.77.42:59504: remote error: tls: bad certificate
2021/06/06 09:35:21 http: TLS handshake error from 10.77.77.42:59516: remote error: tls: bad certificate
2021/06/06 09:35:21 http: TLS handshake error from 10.77.77.42:59528: remote error: tls: bad certificate
2021/06/06 09:35:22 http: TLS handshake error from 10.77.77.42:59534: remote error: tls: bad certificate
2021/06/06 09:35:22 http: TLS handshake error from 10.77.77.42:59550: remote error: tls: bad certificate
2021/06/06 09:35:22 http: TLS handshake error from 10.77.77.42:59564: remote error: tls: bad certificate
2021/06/06 09:35:22 http: TLS handshake error from 10.77.77.42:59582: remote error: tls: bad certificate
2021/06/06 09:35:22 http: TLS handshake error from 10.77.77.42:59592: remote error: tls: bad certificate
2021/06/06 09:35:23 http: TLS handshake error from 10.77.77.42:59636: remote error: tls: bad certificate
2021/06/06 09:35:23 http: TLS handshake error from 10.77.77.42:59640: remote error: tls: bad certificate
2021/06/06 09:35:23 http: TLS handshake error from 10.77.77.42:59684: remote error: tls: bad certificate
2021/06/06 09:35:24 http: TLS handshake error from 10.77.77.42:59690: remote error: tls: bad certificate
2021/06/06 09:35:25 http: TLS handshake error from 10.77.77.42:59792: remote error: tls: bad certificate
2021/06/06 09:35:25 http: TLS handshake error from 10.77.77.42:59800: remote error: tls: bad certificate

```

I have the same setup in other 1.18.x clusters and all seems to work fine for more months now.

Would you have any clues or pointers?

**Comment by kikyomits** [comment]
Thank you for keep using sts-annotator. I can try to reproduce your issue in my k8s (currently v1.18.17-gke.100). But can you provide some info?

- How often this error occurred? Is this error repeated every statefulset deployment or only sometimes?
- TLS verify commands you ran and their results
- your `config.yaml` file

---

The error logs are generated by http client module, which means `sts-annotator` failed to connect to kubernetes api  (e.g. `https://kubernetes.default.svc` in default. ) due to unmatched certificate.

My first guess is that your CA used in sts-annotator does not match to the certificate used by kube api server. Although you said you verified it, let me do double check by seeing your `config.yaml` and TLS verification commands and their results.

The Certificate Authority and k8s api endpoint are defined in `config.yaml`.

```yaml
k8s:
  url: https://kubernetes.default.svc
  token: /run/secrets/sts-annotator/token
  tls:
    caCert: /run/secrets/sts-annotator/ca.crt
```

My second guess is that I might need to add more options to http client. Current client config is only setting. Might need `TLSHandshakeTimeout` if it takes more than 100ms to establish TLS connection between `sts-annotator` and kuberenetes api in you environment. In the worst case, I can add an option to ignore TLS verification.

```go
	CLIENT = &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				RootCAs: caCertPool,
			},
		},
	}
```

**Comment by smg-bg** [comment]
Thanks for the quick follow up! I've started using the sts-annotator as a temporary workaround until https://github.com/kubernetes/kubernetes/issues/40651 is closed. It seems that this won't happen soon :) 

Here is my config.yaml:

```yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: sts-annotator
  namespace: sts-annotator
data:
  config.yaml: |-
    server:
      mode: release
      log:
        level: debug
      port: 8443
      tls:
        cert: /run/secrets/sts-annotator/server.crt
        key: /run/secrets/sts-annotator/server.key
    k8s:
      url: https://kubernetes.default.svc
      token: /run/secrets/kubernetes.io/serviceaccount/token
      tls:
        caCert: /run/secrets/kubernetes.io/serviceaccount/ca.crt

```

I've noticed that your paths in the above reply are under /run/secrets/sts-annotator, but based on the examples under the deployment folder, and that makes sense after all, the token and the ca.crt file are taken from /run/secrets/kubernetes.io. Maybe a typo?!

It happens all the time for all statefulsets deployed in the cluster. I doubt it is a timeout issue. 

I start to believe that there is a version incompatibility that is used from the K8s API and the error is just misleading. I've started looking in more detail in the code of sts-annotator, but unfortunately I'm anything but proficient with Go programming... Maybe something I need to put higher in my list :) 

Thanks again for your help!

**Comment by smg-bg** [comment]
@mk811 I found where the problem is and that is not in the code of sts-annotator. I created the server certificates incorrectly at the very beginning, which somehow worked in the _v1beta_ version. With 1.19.x and the release of _v1_ the rules became much more stricter and that broke the service. 

I can provide some code snippets in the coming days of how I created the CSRs in case that is helpful for anyone else who falls in the same trap as me :-)

**Comment by kikyomits** [comment]
@smg-bg thanks for the updates. Great to hear you found a resolution of this issue. 

> I can provide some code snippets in the coming days of how I created the CSRs in case that is helpful for anyone else who falls in the same trap as me :-)

This is great. Please share it on this issue or update Readme and raise a PR.

I also found several places to be updated for better user experience and `v1` version. Will work on it shortly.

**Comment by kikyomits** [comment]
Hi @smg-bg 
I've released new version of sts-annotator to address dependency vulnerability. Along with that, I also added the detailed steps to generate certificate in README.md. Let me close this issue. Thanks.
